### ISSUE TITLE
修复对象数组缩进，希望采纳。

### ISSUE THREAD

**Issue by momoca** [qiuquanwu/vue3-json-viewer#29]
修复前
![image](https://github.com/user-attachments/assets/942b80af-fa58-44c3-a21d-ca7fdd635c7b)
修复后
![image](https://github.com/user-attachments/assets/157a5116-34b2-4813-b68e-3d9fb635846c)

```css
  .jv-node .jv-toggle.open + .jv-key + .jv-push > .jv-item.jv-object:last-of-type,
  .jv-node .jv-toggle.open + .jv-key + .jv-push > .jv-item.jv-array:last-of-type,
  .jv-node .jv-toggle.open + .jv-key + .jv-push > .jv-node:last-of-type {
    margin-left: 12px;
  }
  .jv-node .jv-toggle:not(.open) + .jv-key + .jv-push > .jv-item.jv-object:last-of-type,
  .jv-node .jv-toggle:not(.open) + .jv-key + .jv-push > .jv-item.jv-array:last-of-type,
  .jv-node .jv-toggle:not(.open) + .jv-key + .jv-push > .jv-node:last-of-type {
    margin-left: 0;
  }
````
